const SYSTEM = {
  DUPLICATE_RADIUS_MINOR_M: 100,
  DUPLICATE_RADIUS_MAJOR_M: 500,
  DUPLICATE_WINDOW_HOURS: 3,
  EARTH_RADIUS_M: 6378137,
  SCORE_VALID: 10,
  SCORE_FALSE: -20,
  FLAG_THRESHOLD: -40,
  NEARBY_DEFAULT_RADIUS_M: 5000,
  NEARBY_MAX_RESULTS: 100,
};

module.exports = SYSTEM;